/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smf.gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import smf.controller.ArticulosJpaController;
import smf.controller.ClientesJpaController;
import smf.gui.reportes.ReportesFrame;
import smf.util.datamodels.DefGSVCol;
import smf.util.datamodels.ItemBuscarDM;
import smf.util.datamodels.JTableColumn;
import smf.util.datamodels.TableHeadMouseAdapter;
import smf.util.datamodels.rows.FilaItemBuscar;

/**
 *
 * @author manuel.japon
 */
public class SelectItemFrame extends BaseFrame {
    
    private ClientesJpaController clientesController;    
    private ArticulosJpaController articulosController;
    private List<JTableColumn> columns;
    private ItemBuscarDM datamodel;
    private String tipo;
    private ReportesFrame parentFrame;
        
    /**
     * Creates new form SelectCliFrame
     */
    public SelectItemFrame(String tipo, ReportesFrame parentFrame) {
        initComponents();        
        clientesController = new ClientesJpaController(em);
        articulosController = new ArticulosJpaController(em);
        this.tipo = tipo;//A: Articulos, C:Clientess
        this.parentFrame = parentFrame;
        
        initColumns();
        
        if ("A".equalsIgnoreCase(tipo)){
            datamodel = new ItemBuscarDM(columns, articulosController);
        }
        else if ("C".equalsIgnoreCase(tipo)){
            datamodel = new ItemBuscarDM(columns, clientesController);
        }
        
        jTable1.setModel(datamodel);
        jTable1.getTableHeader().addMouseListener(new TableHeadMouseAdapter(jTable1, datamodel));
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()) {
                    updateStatusSelectBtn();
                }
            }
        });
        
         jTable1.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {                
                if (mouseEvent.getClickCount() == 2) {
                    doSelectionAction();                    
                }
            }
        });
        
        doFilter();
    }
    
     public void updateStatusSelectBtn(){
        int[] selectedRows = jTable1.getSelectedRows();
        jButtonSelect.setEnabled( selectedRows.length>0 );
    }
     
    public void initColumns(){        
        
        String[][] columnsMatrix = new String[][] { 
                { "NUI", "cli_ci", "2" }, 
                { "Nombres y Apellidos", "nomapel", "1" },
                { "CODBAR", "art_codbar","2" }, 
                { "Nombre", "art_nombre","1" }
            };
        
        String[] datosColId=null;
        String[] datosColDesc=null;
        if (tipo.equalsIgnoreCase("A")){
            datosColId = columnsMatrix[2];
            datosColDesc = columnsMatrix[3];
        }
        else if (tipo.equalsIgnoreCase("C")){
            datosColId = columnsMatrix[0];
            datosColDesc = columnsMatrix[1];
        }
        
        columns = new ArrayList<>();
        
        columns.add(
                new JTableColumn<FilaItemBuscar>(
                        0,
                        datosColId[0],
                        datosColId[1],
                        String.class,
                        new DefGSVCol<FilaItemBuscar>(){
                            @Override
                            public Object getValueAt(FilaItemBuscar row, int rowIndex) {
                                return row.getCodeItem();
                            }                            
                        }
                )
        );
        
        columns.add(
                new JTableColumn<FilaItemBuscar>(
                        1,
                        datosColDesc[0],
                        datosColDesc[1],
                        String.class,
                        new DefGSVCol<FilaItemBuscar>(){
                            @Override
                            public Object getValueAt(FilaItemBuscar row, int rowIndex) {
                                return row.getDescItem();
                            }                            
                        }
                )
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTFFiltro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonSelect = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelTitulo.setText("Búsqueda");
        jPanel4.add(jLabelTitulo);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTFFiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFiltroKeyReleased(evt);
            }
        });
        jPanel5.add(jTFFiltro, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        jButtonSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smf/gui/icons/icons8-checkmark.png"))); // NOI18N
        jButtonSelect.setText("Elegir");
        jButtonSelect.setEnabled(false);
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSelect);

        btnClose.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smf/gui/icons/icons8-close_pane_filled.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jTFFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFiltroKeyReleased
        doFilter();
    }//GEN-LAST:event_jTFFiltroKeyReleased

    public void doSelectionAction(){
        int[] rows = jTable1.getSelectedRows();
       try{
           FilaItemBuscar row = datamodel.getValueAt(rows[0]);
           //showMsg("Item Selecionado:" + row.getDescItem());
           this.parentFrame.doSelectItem(row, tipo);
           setVisible(false);
        }
        catch(Throwable ex){
            showMsgError(ex);
        }
    }
    
    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
       
        doSelectionAction();
    }//GEN-LAST:event_jButtonSelectActionPerformed

    
     public void doFilter(){
        String filtro = this.jTFFiltro.getText().trim();
        //if (filtro.length()>0){
            try{                                
                datamodel.setFiltro(filtro);
                datamodel.loadFromDataBase();
                datamodel.fireTableDataChanged();
            }
            catch(Throwable ex){
                showMsgError(ex);
            }
        //}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFiltro;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
