/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smf.gui;

import java.awt.Image;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import smf.controller.EmpresaJpaController;
import smf.entity.Empresa;

/**
 *
 * @author manuel.japon
 */
public class SplashScreen extends BaseFrame {
    
    EmpresaJpaController  empresaController;
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        empresaController = new EmpresaJpaController(em);
    }
    
    public void loadImage(){
        Image img = null;
        try {
            Empresa empresa = empresaController.getDatosEmpresa();
            String path = null;
            if (empresa != null && empresa.getEmpLogo() != null && empresa.getEmpLogo().trim().length()>0){
                path =  empresa.getEmpLogo().trim();
            }
            
            if (path != null){
                img = ImageIO.read(new File(path));
            }
            else{
                img =ImageIO.read(SmartFactMain.class.getResource("/smf/gui/icons/deftimg.jpg"));
            }
            
            Image dimg = img.getScaledInstance(jLabelImg.getWidth(), jLabelImg.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            jLabelImg.setIcon(imageIcon);
            
        } catch (Throwable e) {
            logError(e);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SmartFact");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel2.setText("Iniciando...");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jLabelImg, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
