/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smf.gui.merc;

import java.math.BigDecimal;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import smf.controller.ArticulosJpaController;
import smf.entity.Articulos;
import smf.gui.BaseFrame;
import smf.gui.SmartFactMain;
import smf.util.ErrorValidException;
import smf.util.StringUtil;

/**
 *
 * @author Usuario
 */
public class EditCodBarraFrame extends BaseFrame {

    /**
     * Creates new form EditCodBarraFrame
     */
    
    private MercaderiaFrame parent;
    private Articulos item;
    private ArticulosJpaController controller;
    
    public EditCodBarraFrame(MercaderiaFrame parent, Articulos artEdited) {
        initComponents();
        this.parent = parent;
        controller = new ArticulosJpaController(em);
        
        item = artEdited;
        this.jLabelArtName.setText( item.getArtNombre() );
        this.jTFCurrentBC.setText(item.getArtCodbar());
        this.jTFNewBarCode.setText(item.getArtCodbar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelArtName = new javax.swing.JLabel();
        jTFNewBarCode = new javax.swing.JTextField();
        jTFCurrentBC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBtnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Editar el código de barra");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Artículo:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nuevo Código:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Código Actual:");

        jLabelArtName.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabelArtName.setText("Artículo:");

        jTFNewBarCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFNewBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNewBarCodeActionPerformed(evt);
            }
        });

        jTFCurrentBC.setEditable(false);
        jTFCurrentBC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCurrentBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCurrentBCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelArtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addComponent(jTFNewBarCode)
                    .addComponent(jTFCurrentBC))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelArtName)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFCurrentBC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNewBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        jBtnSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smf/gui/icons/Save_20px.png"))); // NOI18N
        jBtnSave.setText("Guardar");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnSave);

        btnClose.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smf/gui/icons/icons8-close_pane_filled.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        
        this.setVisible(false);

    }//GEN-LAST:event_btnCloseActionPerformed

    private void jTFNewBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNewBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNewBarCodeActionPerformed

    private void jTFCurrentBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCurrentBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCurrentBCActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        try {
            if (StringUtil.isEmpty(this.jTFNewBarCode.getText())) {
                showMsg("Debe ingresar el nuevo código de barra");
            } else {
                if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea cambiar el código de barra para este artículo?", "", JOptionPane.YES_NO_OPTION) == 0) {
                    String newCodBarra = this.jTFNewBarCode.getText().trim();
                    if (!newCodBarra.trim().toUpperCase().equalsIgnoreCase(item.getArtCodbar().trim().toUpperCase())) {
                        if (controller.yaExisteBarcode(newCodBarra.trim())) {
                            showMsg("El código de barra:" + newCodBarra + " ya ha sido registrado, no se puede actualizar");
                            return;
                        }
                    }
                    this.controller.actualizarCodBarra(item.getArtId(), this.jTFNewBarCode.getText().trim());
                    SmartFactMain.showSystemTrayMsg("Actualización exitosa");
                    item.setArtCodbar(this.jTFNewBarCode.getText().trim());
                    this.parent.reloadArts();                    
                    this.parent.updateArticulos();
                    setVisible(false);
                }
            }
        } catch (Throwable ex) {
            showMsgError(ex);
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelArtName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFCurrentBC;
    private javax.swing.JTextField jTFNewBarCode;
    // End of variables declaration//GEN-END:variables
}
